name: Build & release
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ${{ matrix.dist }}
    name: ${{ matrix.goos }} ${{ matrix.goarch }} build
    strategy:
      matrix:
        include:
          - dist: ubuntu-latest
            goos: linux
            goarch: arm64
          - dist: ubuntu-latest
            goos: linux
            goarch: amd64
    steps:
    - uses: actions/checkout@v3

    - name: Set version
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make misc/version

    - name: Download dictionaries
      run: make static/dictionaries

    - name: Download sentences
      run: make static/sentences

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOPATH: /home/runner/work/fb2converter/fb2converter
      run: make build/fb2c
    
    - name: Compress
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: zip fb2c-${GOOS}-${GOARCH}-${GITHUB_REF##*/}.zip build/fb2c

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: fb2c-*.zip
